server:
  port: 8081

spring:
  application:
    name: dispatcher

  redis:
    host: localhost
    port: 6379
    timeout: 1000ms

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    name: ${TELEGRAM_BOT_NAME}

url:
  auth: http://localhost:8080/api/auth
  account: http://localhost:8080/api/account
  transfer: http://localhost:8080/api/transfer

jwt:
  redis-prefix: "jwt:telegram:"
  ttl-hours: 12

transfer:
  redis-prefix: "txpair:"
  ttl-seconds: 90


